# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44b48e4068070c5c1e846d73e99197d8116ae4b2ea2174dd341929cb855a7a57f798a69eaee1a3276752e2a3f7af649be6ed283944cf378ba0a67aa12536885d

test:
  secret_key_base: 8b7e1aca3b73ffffe932abe212f497d1bdd3367235b373d69fc21989f19027f74c6c5db9f5519fc7f00c41c303d85e1955795374a4a0b1be3347cbf2245b5b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
